# Generated by Django 4.0.4 on 2022-05-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('contact_us_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=1500)),
                ('message', models.CharField(max_length=1500)),
            ],
        ),
    ]
