# Generated by Django 4.0.4 on 2022-05-10 07:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='awbresponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_assign_status', models.CharField(max_length=500)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='giftWrap',
            fields=[
                ('giftwrap_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hubAddress',
            fields=[
                ('hub_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('address_2', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('isd_code', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('send_news_and_Offers', models.BooleanField()),
                ('discount_code', models.CharField(blank=True, max_length=500)),
                ('gifting_msg', models.CharField(blank=True, max_length=500)),
                ('total_amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('payment_status', models.CharField(default='ACTIVE', max_length=500)),
                ('order_status', models.CharField(default='pending', max_length=500)),
                ('tracking_id', models.CharField(blank=True, max_length=500)),
                ('product', models.JSONField()),
                ('shipping_address', models.JSONField()),
                ('billing_address', models.JSONField()),
                ('current_status', models.CharField(choices=[('un attended', 'un attended'), ('printed', 'printed'), ('shipped', 'shipped')], default='un attended', max_length=500)),
                ('country', models.CharField(default='INDIA', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='orderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=500)),
                ('shipment_id', models.CharField(max_length=500)),
                ('status', models.CharField(blank=True, max_length=500)),
                ('status_code', models.CharField(blank=True, max_length=500)),
                ('onboarding_completed_now', models.CharField(blank=True, max_length=500)),
                ('awb_code', models.CharField(blank=True, max_length=500)),
                ('courier_company_id', models.CharField(blank=True, max_length=500)),
                ('courier_name', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='pickupresponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_status', models.CharField(max_length=500)),
                ('pickup_scheduled_date', models.CharField(max_length=500)),
                ('pickup_token_number', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('others', models.JSONField()),
                ('pickup_generated_date', models.JSONField()),
                ('data', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=500)),
                ('product_name', models.CharField(max_length=500, unique=True)),
                ('in_stock', models.BooleanField()),
                ('availability', models.CharField(choices=[('single level', 'single attended'), ('double level', 'double level'), ('triple level', 'triple level')], default='single level', max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='returndata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=500)),
                ('order_date', models.CharField(max_length=500)),
                ('channel_id', models.CharField(max_length=500)),
                ('pickup_customer_name', models.CharField(max_length=500)),
                ('pickup_last_name', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('pickup_address', models.CharField(max_length=500)),
                ('pickup_address_2', models.CharField(max_length=500)),
                ('pickup_city', models.CharField(max_length=500)),
                ('pickup_state', models.CharField(max_length=500)),
                ('pickup_country', models.CharField(max_length=500)),
                ('pickup_pincode', models.CharField(max_length=500)),
                ('pickup_email', models.CharField(max_length=500)),
                ('pickup_phone', models.CharField(max_length=500)),
                ('pickup_isd_code', models.CharField(max_length=500)),
                ('shipping_customer_name', models.CharField(max_length=500)),
                ('shipping_last_name', models.CharField(max_length=500)),
                ('shipping_address', models.CharField(max_length=500)),
                ('shipping_address_2', models.CharField(max_length=500)),
                ('shipping_city', models.CharField(max_length=500)),
                ('shipping_country', models.CharField(max_length=500)),
                ('shipping_pincode', models.CharField(max_length=500)),
                ('shipping_state', models.CharField(max_length=500)),
                ('shipping_email', models.CharField(max_length=500)),
                ('shipping_isd_code', models.IntegerField()),
                ('shipping_phone', models.CharField(max_length=500)),
                ('payment_method', models.CharField(max_length=500)),
                ('total_discount', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('order_items', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='returnOrderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='shipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=500)),
                ('shipment_id', models.CharField(max_length=500)),
                ('awb_code', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('productMedia', models.FileField(upload_to='')),
                ('Message', models.CharField(max_length=500)),
                ('Rating', models.CharField(max_length=500)),
                ('user_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_no',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='printingType',
            fields=[
                ('printing_type_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('printing_type', models.CharField(choices=[('Single Level', 'Single Level'), ('Double Level', 'Double Level'), ('Digital Copy', 'Digital Copy')], max_length=100)),
                ('availability', models.BooleanField()),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='frameSize',
            fields=[
                ('frame_size_id', models.AutoField(primary_key=True, serialize=False)),
                ('frame_size', models.CharField(max_length=500)),
                ('availability', models.BooleanField()),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
