# Generated by Django 4.0.4 on 2022-05-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_awbresponse_giftwrap_hubaddress_order_orderresponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnorderresponse',
            name='order',
        ),
        migrations.AddField(
            model_name='returnorderresponse',
            name='company_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnorderresponse',
            name='shipment_id',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnorderresponse',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnorderresponse',
            name='status_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnorderresponse',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
