# Generated by Django 4.0.4 on 2022-05-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_returnorderresponse_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='trackOrderResponse',
            fields=[
                ('trackOrder_id', models.AutoField(primary_key=True, serialize=False)),
                ('trackOrder_status', models.JSONField()),
            ],
        ),
    ]
