# Generated by Django 4.0.4 on 2022-05-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trackorderresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='productDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('frame_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.framesize')),
            ],
        ),
        migrations.DeleteModel(
            name='shipmentStatus',
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('single level', 'single level'), ('double level', 'double level'), ('Digital Copy', 'Digital Copy')], default='single level', max_length=100),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
