# Generated by Django 4.0.4 on 2022-05-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productdetails_delete_shipmentstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentResponse',
            fields=[
                ('paymentresponse_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='framesize',
            name='frame_size',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
