# Generated by Django 4.0.4 on 2022-05-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_paymentresponse_alter_framesize_frame_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framesize',
            name='frame_size',
            field=models.CharField(max_length=500),
        ),
    ]
